---
- name: Install and configure pykms using docker image
  hosts: local
  become: true

  tasks:
    - name: clone pykms to /tmp
      git:
        repo: https://github.com/SystemRage/py-kms.git
        dest: /tmp/py-kms
  
    - name: Ensure pip3 is installed
      package:
        name: python-pip
        state: present

    - name: Ensure docker python module is installed
      pip:
        name: docker
        state: present

    - name: build docker image
      docker_image:
        build:
          path: /tmp/py-kms/docker/docker-py3-kms
          pull: true
        name: pykms/pykms
        tag: py3-kms
        source: build
        state: present
      register: docker_result

    - name: create the docker image using docker build
      debug:
        msg: "Image build successful"
      when: not docker_result.failed

    - name: start container
      docker_container:
        name: py3-kms
        image: "pykms/pykms:py3-kms"
        state: started
        tty: true
        published_ports:
          - '8080:8080'
          - '1688:1688'
        env:
          IP: '0.0.0.0'
          PORT: '1688'
          SQLITE: 'true'
          HWID: 'RANDOM'
          LOGLEVEL: 'INFO'
          LOGFILE: '/var/log/py3-kms.log'
          LOGSIZE: '2'
        volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/var/log:/var/log:rw'
        restart_policy: always
      when: not docker_result.failed
