---
- name: Install all the desired packages
  hosts: local

  vars:
    packages:
      - docker

  tasks:
    - name: Install All packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

