---
- name: Install or Update and configure pihole using docker image
  hosts: local
  become: true
  gather_facts: false

  tasks:
    - name: Ensure pip3 is installed
      package:
        name: python-pip
        state: present

    - name: Ensure docker python module is installed
      pip:
        name: docker
        state: present

    - name: Pull docker image from docker registry
      docker_image:
        name: pihole/pihole
        tag: latest
        source: pull
#        force_source: true
        state: present
      register: docker_result

    - name: Docker Build Debug message
      debug:
        msg: "Image pull successful"
      when: not docker_result.failed

    - name: Remove the existing Docker image
      docker_container:
        name: pihole
        state: absent
        force_kill: true
        container_default_behavior: compatibility
      when: not docker_result.failed

    - name: start container
      docker_container:
        name: pihole
        image: "pihole/pihole:latest"
        state: started
        tty: true
        published_ports:
          - '53:53/tcp'
          - '53:53/udp'
          - '80:80'
          - '443:443'
        #network_mode: host
        env:
          TZ: 'Europe/London'
          VIRTUAL_HOST: 'pi.hole'
          PROXY_LOCATION: 'pi.hole'
          WEBPASSWORD: "{{ pi_pass }}"
        hostname: pi.hole
        volumes:
          - '~/etc-pihole/:/etc/pihole/'
          - '~/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        restart_policy: unless-stopped
        capabilities:
          - NET_ADMIN
        privileged: true
        container_default_behavior: compatibility
      when: not docker_result.failed

