---
- name: Install all the desired packages
  hosts: local
  gather_facts: true

  vars:
    manjaro_family: Archlinux
    ubuntu_family: Debian


  tasks:
    - name: Ensure correct distro vars are loaded
      include_vars: "vars/{{ ansible_os_family }}.yml"

    - name: Ensure the System is up-to-date (pacman -Syu)
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == manjaro_family

    - name: Ensure pre-req apt packages are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ ubuntu_pre_packages }}"
      when: ansible_os_family == ubuntu_family

    - name: Install the Docker apt repo key
      apt_key:
        url: "{{ item }}"
        state: present
      when: ansible_os_family == ubuntu_family
      loop: "{{ ubuntu_repo_keys }}"
      vars:
        ubuntu_repo_keys:
          - https://download.docker.com/linux/ubuntu/gpg

    - name: Download the Microsoft GPG Key
      shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
      when: ansible_os_family == ubuntu_family
      changed_when: false

    - name: Ensure the gpg file is in the correct place
      copy:
        src: /tmp/packages.microsoft.gpg
        dest: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == ubuntu_family

    - name: Get Ubuntu release
      command: lsb_release -cs
      register: release
      when: ansible_os_family == ubuntu_family

    - name: Ensure required Apt repos are present on Ubuntu
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ ubuntu_repo_urls }}"
      when: ansible_os_family == ubuntu_family
      vars:

    - name: Install All ubuntu packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: 
        - "{{ ubuntu_docker_packages }}"
        - "{{ ubuntu_packages }}"
      when: ansible_os_family == ubuntu_family

    - name: Install All manjaro packages
      pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ manjaro_packages }}"
      when: ansible_os_family == manjaro_family

    - name: Ensure containerd and docker are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - containerd
        - docker


