---
- name: Install all the desired packages
  hosts: local

  vars:
    packages:
      - docker

  tasks:
    - name: Install All packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Ensure containerd and docker are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - containerd
        - docker


