---
- name: Install all the desired packages
  hosts: local
  gather_facts: false

  vars:
    packages:
      - docker
      - lastpass-cli
      - tree

  tasks:
    - name: Ensure the System is up-to-date (pacman -Syu)
      pacman:
        update_cache: true
        upgrade: true

    - name: Install All packages
      pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Ensure containerd and docker are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - containerd
        - docker


