---
- name: Ensure pip3 is installed on Ubuntu
  package:
    name: python3-pip
    state: present

- name: Ensure DNS Stub is disabled for systemd-resolved on Ubuntu
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^#DNSStubListener=yes"
    line: "DNSStubListener=no"

- name: Ensure /etc/resolved.conf points to the correct file
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  notify: Restart systemd-resolved
