---
- name: Ensure the System is up-to-date (apt update)
  apt:
    update_cache: true

- name: Ensure pre-req apt packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ ubuntu_pre_packages }}"
  
- name: Install the Docker apt repo key
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ ubuntu_repo_keys }}"

# - name: Download the Microsoft GPG Key
#   shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
#   changed_when: false

# - name: Ensure the gpg file is in the correct place
#   copy:
#     src: /tmp/packages.microsoft.gpg
#     dest: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
#     owner: root
#     group: root
#     mode: '0644'

- name: Get Ubuntu release
  command: lsb_release -cs
  register: release
  changed_when: false
 
- name: Ensure required Apt repos are present on Ubuntu
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ ubuntu_repo_urls }}"

- name: Ensure the System is up-to-date (apt update)
  apt:
    update_cache: true

- name: Install All ubuntu packages
  apt:
    name: "{{ item }}"
    state: present
  loop: 
    - "{{ ubuntu_packages }}"
    - "{{ ubuntu_docker_packages }}"

# - name: Prevent docker from being upgraded # this is no longer needed since 5:20.10.6~3-0~ubuntu-focal arm64
#   dpkg_selections:
#     name: "{{ item }}"
#     selection: hold
#   loop: "{{ ubuntu_docker_hold_packages }}"

- name: Add the {{ ansible_ssh_user }} to the docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: true

- name: Download the cockpit-docker package that works with Ubuntu 20.04
  get_url:
    url: https://launchpad.net/ubuntu/+source/cockpit/215-1~ubuntu19.10.1/+build/18889196/+files/cockpit-docker_215-1~ubuntu19.10.1_all.deb
    dest: /tmp/cockpit-docker_215-1~ubuntu19.10.1_all.deb

- name: Install the cockpit-docker package
  apt:
    deb: /tmp/cockpit-docker_215-1~ubuntu19.10.1_all.deb

- name: Ensure the netplan config contains the right configuration
  blockinfile:
    path: /etc/netplan/50-cloud-init.yaml
    block: |
      network:
          version: 2
          renderer: NetworkManager    # This is the changed line. Default is networkd
          ethernets:
              eth0:      # This is different by hardware.
                  dhcp4: true
    validate: /usr/sbin/netplan try

- name: Reboot the Raspberry PI 
  reboot:
