---
ansible_python_interpreter: /usr/bin/python3

ubuntu_repo_urls:
  - "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"

ubuntu_repo_keys:
  - https://download.docker.com/linux/ubuntu/gpg

ubuntu_pre_packages:
  - python3-apt
  - apt-transport-https
  - software-properties-common
ubuntu_packages:
  - lastpass-cli
  - tree
  - net-tools

# docker bug requires the use of docker version 19 so these packages are stuck on the latest 19 version
# the bug incorrectly recognises arm64 and pulls the amd64 image, actually it pulls the correct image
# but the image manifests incorrectly lists the image as amd64 instead of arm64
# the result is that the docker can't/won't run the image...
# the version pinning is currently set to ubuntu focal fossa (20.04), this would need to change for other debian families
ubuntu_docker_packages:
  - docker-ce=5:19.03.15~3-0~ubuntu-focal 
  - docker-ce-cli=5:19.03.15~3-0~ubuntu-focal
  - containerd.io
ubuntu_docker_hold_packages:
  - docker-ce
  - docker-ce-cli

